/* Database schema to keep the structure of entire database. */

CREATE TABLE animal (
   id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name varchar(100) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date NOT NULL,
    escape_attempts integer NOT NULL,
    neutered boolean,
    weight_kg numeric NOT NULL,
    CONSTRAINT animals_pkey PRIMARY KEY (id)
);

ALTER TABLE animal
DROP COLUMN species,
ADD COLUMN species_id INT,
ADD CONSTRAINT species_key
FOREIGN KEY (species_id)
REFERENCES species(id),
ADD COLUMN owner_id INT,
ADD CONSTRAINT owner_key
FOREIGN KEY (owner_id)
REFERENCES owners(id);

CREATE TABLE owners (
  id INT GENERATED ALWAYS AS IDENTITY,
  full_name TEXT,
  age INT,
  PRIMARY KEY(id)
);

CREATE TABLE species (
  id INT GENERATED ALWAYS AS IDENTITY,
  name TEXT,
  PRIMARY KEY(id)
);

CREATE TABLE specializations (
  vet_id INT,
  species_id INT,
  FOREIGN KEY (vet_id) REFERENCES vets(id),
  FOREIGN KEY (species_id) REFERENCES species (id),
  PRIMARY KEY (vet_id, species_id)
);

CREATE TABLE visits (
  animal_id INT,
  vet_id INT,
  visit_date DATE,
  FOREIGN KEY (animal_id) REFERENCES animal (id),
  FOREIGN KEY (vet_id) REFERENCES vets (id),
);

ALTER TABLE owners ADD COLUMN email VARCHAR(120);


CREATE INDEX animal_id_asc ON visits (animal_id ASC);
DROP INDEX animal_id_asc;

CREATE INDEX vet_id_ind ON visits(vet_id);
DROP INDEX vet_id_ind;

CREATE INDEX owners_email_asc ON owners (email ASC);
DROP INDEX owners_email_asc;